name: Infection

on:
  workflow_call: &default_conditions
    paths:
      - '**.php'
      - 'infection.json5'
  pull_request: *default_conditions
  push: *default_conditions

jobs:
  run_mutation_tests:
    uses: phonyland/dev-tools/.github/workflows/infection.yml@master
