name: Infection

on:
  pull_request:
    paths:
      - '**.php'
      - 'infection.json5'
  push:
    paths:
      - '**.php'
      - 'infection.json5'

jobs:
  run_mutation_tests:
    uses: phonyland/dev-tools/.github/workflows/infection.yml@master
