name: PHPstan

on:
  pull_request:
    paths:
      - '**.php'
      - 'phpstan.neon.dist'
  push:
    paths:
      - '**.php'
      - 'phpstan.neon.dist'

jobs:
  phpstan:
    uses: phonyland/dev-tools/.github/workflows/phpstan.yml@master
