name: PHPstan

on:
  workflow_call: &default_conditions
    paths:
      - '**.php'
      - 'phpstan.neon.dist'
  pull_request: *default_conditions
  push: *default_conditions

jobs:
  phpstan:
    uses: phonyland/dev-tools/.github/workflows/phpstan.yml@master
