name: Pint

on:
  workflow_call: &default_conditions
    paths:
      - '**.php'
  pull_request: *default_conditions
  push: *default_conditions

jobs:
  check_code_styling:
    uses: phonyland/dev-tools/.github/workflows/pint.yml@master
